(()=>{
const $=id=>document.getElementById(id), N=v=>{const m=String(v??'').replace(/[$,%]/g,'').replace(/,/g,'').match(/-?[\d.]+/);return m?+m[0]:0}, E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), money=v=>'$'+N(v).toLocaleString(undefined,{maximumFractionDigits:0});
const units=x=>window.tab4MetricMode==='estimate'?N(x.bsrEstimatedUnitsMid):window.tab4MetricMode==='actual'?N(x.myUnits):(N(x.myUnits)||N(x.bsrEstimatedUnitsMid)), revenue=x=>window.tab4MetricMode==='estimate'?N(x.bsrEstimatedRevenueMid):window.tab4MetricMode==='actual'?N(x.myRevenue):(N(x.myRevenue)||N(x.bsrEstimatedRevenueMid)), stamp=x=>new Date(x.snapshotAt||x.lastUpdated||x.lastChecked||0).getTime();
let prefs={timeframe:'30',order:[],hidden:[],contribution:'revenue',parentMetric:'revenue'};
const storeGet=k=>new Promise(r=>chrome.storage.local.get(k,r)), storeSet=o=>new Promise(r=>chrome.storage.local.set(o,r));
function state(){return window.myPortfolioState?.()||{products:[],history:{},view:[]}}
function timeframeMs(){return prefs.timeframe==='all'?Infinity:N(prefs.timeframe)*864e5}
function periodHistory(asin){const h=state().history[asin]||[],cut=Date.now()-timeframeMs();return prefs.timeframe==='all'?h:h.filter(x=>stamp(x)>=cut)}
function baseline(asin){const h=state().history[asin]||[],target=Date.now()-timeframeMs();return prefs.timeframe==='all'?h[0]:[...h].reverse().find(x=>stamp(x)<=target)}
function change(current,base,rank=false){if(!base||!N(base))return null;let v=(N(current)-N(base))/Math.abs(N(base));return rank?-v:v}
function fmtChange(v){return v==null?'New / no baseline':`${v>=0?'▲':'▼'} ${Math.abs(v*100).toFixed(1)}%`}
function getSections(){return[...document.querySelectorAll('#myproducts > details.mySection')].map((el,i)=>{if(!el.dataset.sectionId)el.dataset.sectionId='s'+i+'-'+(el.querySelector('summary')?.textContent||'section').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,35);return el})}
function sectionName(el){return(el.querySelector('summary')?.textContent||'Section').trim()}
async function savePrefs(){await storeSet({tab4Preferences:prefs})}
function applyLayout(){const page=$('myproducts'),sections=getSections(),map=new Map(sections.map(x=>[x.dataset.sectionId,x]));for(const id of prefs.order){const el=map.get(id);if(el)page.insertBefore(el,$('myStatus'))}for(const el of sections)if(!prefs.order.includes(el.dataset.sectionId))page.insertBefore(el,$('myStatus'));for(const el of sections)el.classList.toggle('sectionHidden',prefs.hidden.includes(el.dataset.sectionId));renderCustomizer()}
function renderCustomizer(){const list=$('proSectionList');if(!list)return;list.innerHTML=getSections().map(el=>`<div class="sectionChoice" draggable="true" data-id="${el.dataset.sectionId}"><span class="dragDots">⠿</span><label class="switch"><input type="checkbox" ${prefs.hidden.includes(el.dataset.sectionId)?'':'checked'}><i></i></label><span>${E(sectionName(el))}</span></div>`).join('');list.querySelectorAll('.sectionChoice input').forEach(input=>input.onchange=async e=>{const id=e.target.closest('.sectionChoice').dataset.id;prefs.hidden=e.target.checked?prefs.hidden.filter(x=>x!==id):[...new Set([...prefs.hidden,id])];applyLayout();await savePrefs()});let drag=null;list.querySelectorAll('.sectionChoice').forEach(row=>{row.ondragstart=()=>{drag=row;row.classList.add('dragging')};row.ondragend=async()=>{row.classList.remove('dragging');prefs.order=[...list.children].map(x=>x.dataset.id);applyLayout();await savePrefs()};row.ondragover=e=>{e.preventDefault();if(!drag||drag===row)return;const r=row.getBoundingClientRect();list.insertBefore(drag,e.clientY<r.top+r.height/2?row:row.nextSibling)}})}
function classify(x){const a=String(x.availability||'').toLowerCase();if(/currently unavailable|out of stock|no active offer/.test(a))return'Out of stock';if(/only\s+\d+\s+left/.test(a))return'Low stock';if(N(x.priceNumber)||N(x.price)||/in stock|available|ships within/.test(a))return'In stock';return'Likely out of stock'}
function metricValue(x,k){if(k==='revenue')return revenue(x);if(k==='units')return units(x);if(k==='reviews')return N(x.reviewCount);if(k==='rank')return N(x.subcategoryRank)?1/N(x.subcategoryRank):0;if(k==='mainRank')return N(x.rank)?1/N(x.rank):0;return 0}
function metricLabel(k,v){if(k==='revenue')return money(v);if(k==='rank'||k==='mainRank')return v?`Strength ${v.toFixed(5)}`:'N/A';return Math.round(v).toLocaleString()}
function renderContribution(){const box=$('myShare');if(!box)return;const products=state().view||state().products,k=prefs.contribution,groups={};for(const x of products){const c=x.mySubcategory||x.rankedSubcategory||'Uncategorized';(groups[c]||(groups[c]=[])).push(x)}const colors=['#2563eb','#14b8a6','#f59e0b','#ec4899','#8b5cf6','#ef4444','#64748b'];box.innerHTML=Object.entries(groups).map(([cat,items])=>{const sorted=[...items].sort((a,b)=>metricValue(b,k)-metricValue(a,k)),total=sorted.reduce((s,x)=>s+metricValue(x,k),0)||1;let deg=0;const grad=sorted.slice(0,8).map((x,i)=>{const st=deg;deg+=metricValue(x,k)/total*360;return`${colors[i%colors.length]} ${st}deg ${deg}deg`}).join(',');return`<article class="shareCard"><header><span class="sectionIcon">◔</span><div><b>${E(cat)}</b><small>${sorted.length} ASINs · ${E(k)}</small></div></header><div class="shareDonut proDonut" style="background:conic-gradient(${grad||'#e2e8f0 0 360deg'})"></div><div class="shareRows">${sorted.slice(0,8).map((x,i)=>`<div><img src="${E(x.imageLink||'icon128.png')}" onerror="this.src='icon128.png'"><i style="background:${colors[i%colors.length]}"></i><span>${E(x.sku||x.asin)}</span><b>${(metricValue(x,k)/total*100).toFixed(1)}%</b><em>${E(metricLabel(k,metricValue(x,k)))}</em></div>`).join('')}</div></article>`}).join('')||'<div class="emptyState">No products match the current filters.</div>'}
function renderParents(){const products=state().view||state().products,k=prefs.parentMetric,groups={};for(const x of products){const parent=x.parentAsin||x.familyKey||x.asin;(groups[parent]||(groups[parent]=[])).push(x)}const sorted=Object.entries(groups).map(([parent,children])=>({parent,children,value:children.reduce((s,x)=>s+metricValue(x,k),0)})).sort((a,b)=>b.value-a.value),grand=sorted.reduce((s,x)=>s+x.value,0)||1;$('proParentCards').innerHTML=sorted.slice(0,6).map(g=>`<article class="familyCard"><div class="familyHead"><div class="imageStack">${g.children.slice(0,3).map(x=>`<img src="${E(x.imageLink||'icon128.png')}" onerror="this.src='icon128.png'">`).join('')}</div><div><small>Parent / family</small><b>${E(g.parent)}</b></div><span>${(g.value/grand*100).toFixed(1)}%</span></div><strong>${metricLabel(k,g.value)}</strong><div class="familyBar"><i style="width:${g.value/grand*100}%"></i></div><small>${g.children.length} child ASIN${g.children.length===1?'':'s'}</small></article>`).join('');
 $('proParentTable').innerHTML='<table><thead><tr><th>Image</th><th>Parent ASIN</th><th>Child ASIN</th><th>Variation</th><th>Revenue</th><th>Units</th><th>Family contribution</th><th>Period change</th></tr></thead><tbody>'+sorted.flatMap(g=>g.children.sort((a,b)=>metricValue(b,k)-metricValue(a,k)).map(x=>{const base=baseline(x.asin),chg=change(metricValue(x,k),base?metricValue(base,k):null);return`<tr><td><img class="productAvatar" src="${E(x.imageLink||'icon128.png')}" onerror="this.src='icon128.png'"></td><td>${E(g.parent)}</td><td><b>${E(x.asin)}</b></td><td>${E(x.selectedVariation||x.variationType||'Single item')}</td><td>${money(revenue(x))}</td><td>${Math.round(units(x)).toLocaleString()}</td><td>${(metricValue(x,k)/grand*100).toFixed(1)}%</td><td><span class="changePill ${chg==null?'neutral':chg>=0?'positive':'negative'}">${fmtChange(chg)}</span></td></tr>`})).join('')+'</tbody></table>'}
function enhanceTables(){const st=state();const by=new Map(st.products.map(x=>[x.asin,x]));for(const id of ['myTopTable','myLatest','myManage','myPrice','myMainRank','mySubRank','myStock']){const table=$(id)?.querySelector('table');if(!table||table.dataset.enhanced==='yes')continue;table.dataset.enhanced='yes';const head=table.querySelector('thead tr');if(head){const th=document.createElement('th');th.textContent='Product';head.insertBefore(th,head.firstChild)}for(const tr of table.querySelectorAll('tbody tr')){const asin=[...tr.cells].map(c=>c.textContent.trim()).find(v=>/^[A-Z0-9]{10}$/.test(v)),x=by.get(asin);const td=document.createElement('td');td.innerHTML=`<div class="productCell"><img src="${E(x?.imageLink||'icon128.png')}" onerror="this.src='icon128.png'"><div><b>${E(x?.sku||asin||'')}</b><small>${E((x?.name||'').slice(0,60))}</small></div></div>`;tr.insertBefore(td,tr.firstChild)}}}
function updateTimeLabels(){const label=prefs.timeframe==='all'?'all history':`last ${prefs.timeframe} days`;document.querySelectorAll('#myproducts .mySection summary').forEach(s=>{s.title=`Current dashboard timeframe: ${label}`});const note=document.querySelector('.advancedFirst .periodNote');if(note)note.innerHTML=`<b>Selected performance window:</b> ${label}. Change pills compare the latest value with the closest available baseline at the start of this period. WoW and MoM remain available where sufficient history exists.`}
function renderAll(){updateTimeLabels();renderContribution();renderParents();setTimeout(enhanceTables,80)}
async function load(){const o=await storeGet('tab4Preferences');prefs={...prefs,...(o.tab4Preferences||{})};$('proTimeframe').value=prefs.timeframe;$('proContributionMetric').value=prefs.contribution;$('proParentMetric').value=prefs.parentMetric;applyLayout();renderAll()}
$('proTimeframe').onchange=async e=>{prefs.timeframe=e.target.value;await savePrefs();renderAll()};$('proContributionMetric').onchange=async e=>{prefs.contribution=e.target.value;await savePrefs();renderContribution()};$('proParentMetric').onchange=async e=>{prefs.parentMetric=e.target.value;await savePrefs();renderParents()};$('proCustomize').onclick=()=>{$('proCustomizer').classList.remove('hidden');renderCustomizer()};$('proCloseCustomize').onclick=()=>$('proCustomizer').classList.add('hidden');$('proDataGuide').onclick=()=>$('proDataBanner').classList.toggle('hidden');$('proReset').onclick=async()=>{prefs={timeframe:'30',order:[],hidden:[],contribution:'revenue',parentMetric:'revenue'};await savePrefs();location.reload()};
window.renderTab4Pro=renderAll;load();
})();
